<a href="https://colab.research.google.com/github/sarthakshukla74/DATA-SCIENCE/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**ARRAY CREATION**

In [ ]:
import numpy as np
a=np.array([1,2,3])
print(a)
print(type(a))
a.ndim


[1 2 3]
<class 'numpy.ndarray'>


2

**ND ARRAY**

In [ ]:
a1=np.array([[1,2,3],[4,5,6]],dtype=np.int8)
a1
a1.ndim
a1.dtype

dtype('int8')

**ARRAY CREATION USING arange FUNCTION**

In [ ]:
b=np.arange(0,12)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**2D ARRAY CREATION USING arange FUNCTION(Dimensions product should be multiple of size)**

In [ ]:
c=np.arange(16).reshape((2,2,4))
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

**ZERO ARRAY**

In [ ]:
a=np.zeros((4,5),dtype=int)
type(a[0][0])

numpy.int64

**IDENTITY ARRAY**

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**ONE ARRAY**

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

**ATTRIBUTES OF NUMPY**

In [ ]:
a1.size

6

In [ ]:
a1.shape

(2, 3)

In [ ]:
a1.ndim

2

In [ ]:
a.itemsize

8

**NUMPY OPERATIONS**

*SCALAR OPERATIONS*

In [ ]:
p=np.arange(12).reshape(3,4)
q=np.arange(12,24).reshape(3,4)
q*2

array([[24, 26, 28, 30],
       [32, 34, 36, 38],
       [40, 42, 44, 46]])

In [ ]:
q+2

array([[14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25]])

In [ ]:
q**2

array([[144, 169, 196, 225],
       [256, 289, 324, 361],
       [400, 441, 484, 529]])

In [ ]:
q-84

array([[-72, -71, -70, -69],
       [-68, -67, -66, -65],
       [-64, -63, -62, -61]])

*RELATIONAL OPERATIONS*

In [ ]:
q>5

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

*VECTOR OPERATIONS*

In [ ]:
p+q

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
p*q

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [ ]:
j=np.round(np.random.random((10,10)))
j

array([[0., 1., 0., 1., 1., 0., 1., 1., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 1., 1.],
       [1., 0., 0., 1., 1., 1., 0., 1., 0., 1.],
       [0., 0., 1., 0., 1., 1., 1., 1., 0., 1.],
       [0., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 1., 1., 0., 0., 1., 0., 1., 1., 1.],
       [0., 0., 1., 0., 1., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [1., 1., 0., 1., 0., 1., 1., 1., 0., 0.]])

In [ ]:
np.max(p)

np.int64(11)

In [ ]:
np.log(p)

/tmp/ipython-input-87274877.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(p)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [ ]:
np.exp(p)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [ ]:
np.floor(p)

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
np.sin(p)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

**INDEXING AND SLICING**

In [ ]:
k=np.arange(12)
k
k[3:9]

array([3, 4, 5, 6, 7, 8])

In [ ]:
print(q[1,1])
print(q)

17
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
q[1:,1:3]

array([[17, 18],
       [21, 22]])

In [ ]:
q[1:,0:3:2]

array([[16, 18],
       [20, 22]])

In [ ]:
q[0::2,0::3]

array([[12, 15],
       [20, 23]])

In [ ]:
q[1,2]

np.int64(18)

In [ ]:
y=np.arange(24).reshape(6,4)

**FANCY INDEXING**

In [ ]:
y[:, [0, 2, 3]]

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

**MAX USING AXIS**

In [ ]:
np.max(y,axis=1)

array([ 3,  7, 11, 15, 19, 23])

In [ ]:
y[y>4]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23])

In [ ]:
y[(y%2==0) & (y>4)]

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22])

**MEAN SQUARED USING NUMPY**

In [ ]:
import numpy as np
def mean_squared(y_true,y_pred):
  return np.mean(np.square(y_true-y_pred))
y_true=np.array([1,2,3,4,5])
y_pred=np.array([5,6,7,8,8])
x=mean_squared(y_true,y_pred)
print(x)

14.6


**STUDENT AVERAGE**

In [ ]:
maths_scores = np.random.randint(0, 101, size=(10, 3))
print(maths_scores)



avg_each_column = np.mean(maths_scores, axis=0)
print(avg_each_column)

[[53 30  4]
 [92 39 65]
 [56 67 54]
 [ 3 25 59]
 [87 82 43]
 [86 74 23]
 [90 63 56]
 [72 15 63]
 [71 26 69]
 [13 54 78]]
[62.3 47.5 51.4]
